# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.5

pipelines:
  branches:
    master:
      - step:
          caches:
            - pip
          script: # Modify the commands below to build your repository.
            - pip install -e .
            - pip install uliege-decision_process[test]
            - pip install uliege-decision_process[gym]
            - apt-get update && apt-get install -y glpk-utils
            # - pytest --cov=. uliege/tests/ --cov-report term-missing --workers 4 --cov-config=uliege/tests/.coveragerc
  pull-requests:
    "**":
      - step:
          caches:
            - pip
          script: # Modify the commands below to build your repository.
            - pip install -e .
            - pip install uliege-decision_process[test]
            - pip install uliege-decision_process[gym]
            - apt-get update && apt-get install -y glpk-utils
            # - pytest --cov=. uliege/tests/ --cov-report term-missing --workers 4 --cov-config=uliege/tests/.coveragerc
